<x-app-layout title="Bilancio"><header class="mb-4"><span class="eyebrow">IL VALORE DEL TUO LAVORO</span><h1>Bilancio</h1><p class="text-secondary">{{ auth()->user()->role === \App\UserRole::Admin ? 'Riepilogo di tutta l’attività EA-Express.' : 'Importi delle spedizioni assegnate a te e spese che hai registrato.' }}</p></header>
    <nav class="d-flex flex-wrap gap-2 mb-3" aria-label="Periodo bilancio">@foreach(['Oggi'=>now('Europe/Rome')->startOfDay(),'Settimana'=>now('Europe/Rome')->startOfWeek(),'Mese'=>now('Europe/Rome')->startOfMonth()] as $label=>$date)<a class="btn btn-outline-secondary btn-sm" href="{{ route('balance.index',[...request()->only('customer_id'),'from'=>$date->toDateString(),'to'=>now('Europe/Rome')->toDateString()]) }}">{{ $label }}</a>@endforeach</nav>
    <x-ui.filters :reset="route('balance.index')"><div class="filter-field"><x-ui.field name="from" label="Dal" type="date" :value="$period->start->toDateString()" /></div><div class="filter-field"><x-ui.field name="to" label="Al" type="date" :value="$period->end->toDateString()" /></div><div class="filter-field"><label class="form-label" for="balance-customer">Cliente</label><select class="form-select" name="customer_id" id="balance-customer"><option value="">Tutta l’attività</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((int)request('customer_id')===$customer->id)>{{ $customer->name }}</option>@endforeach</select></div></x-ui.filters>
    <section class="balance-summary" aria-label="Sintesi economica"><article class="surface"><span>Lordo incassato</span><strong>{{ \App\Support\Money::format($cash) }}</strong></article><article class="surface"><span>Netto operativo</span><strong>{{ \App\Support\Money::format($operatingNet) }}</strong></article><article class="surface"><span>Netto previsto · inclusi sospesi</span><strong>{{ \App\Support\Money::format($finalNet) }}</strong></article></section>
    <nav class="section-jump" aria-label="Sezioni del bilancio"><a href="#delivery-details">Consegne</a><a href="#cash-details">Incassi</a><a href="#expense-details">Spese</a><a href="#pending-details">Sospesi</a></nav>
    <section class="surface p-4 mb-4"><h2 class="h4">Prospetto contabile</h2><p class="text-secondary small">Criterio di cassa: il lordo comprende gli incassi registrati nel periodo, al netto degli storni. Il valore del pacco non è un ricavo di EA Express. Con il filtro cliente sono escluse le spese generali non attribuite a un cliente.</p><div class="table-responsive"><table class="table accounting-table"><thead><tr><th>Voce</th><th>Origine</th><th class="text-end">Importo</th></tr></thead><tbody>
    @foreach([['Totale lordo incassato','Movimenti di incasso, inclusi saldi dei sospesi',$cash,'cash-details'],['Spese','Spese valide e saldi dei debiti',-$spent,'expense-details']] as [$label,$origin,$amount,$anchor])<tr><th><a href="#{{ $anchor }}">{{ $label }}</a></th><td>{{ $origin }}</td><td class="text-end text-nowrap">{{ \App\Support\Money::format($amount) }}</td></tr>@endforeach
    @if($extraIncome - $extraExpenses + $adjustments !== 0)<tr><th>Saldo delle registrazioni pregresse</th><td>Già incluso nel netto operativo</td><td class="text-end text-nowrap">{{ \App\Support\Money::format($extraIncome - $extraExpenses + $adjustments) }}</td></tr>@endif
    <tr class="table-primary"><th colspan="2">Netto operativo provvisorio</th><td class="text-end text-nowrap fw-bold">{{ \App\Support\Money::format($operatingNet) }}</td></tr>
    <tr><th><a href="#pending-details">Sospesi in entrata</a></th><td>Residui ancora da riscuotere</td><td class="text-end text-nowrap">{{ \App\Support\Money::format($pendingIncoming) }}</td></tr><tr><th><a href="#pending-details">Sospesi in uscita</a></th><td>Residui ancora da pagare</td><td class="text-end text-nowrap">{{ \App\Support\Money::format(-$pendingOutgoing) }}</td></tr><tr><th><a href="#pending-details">Impatto netto dei sospesi ({{ $pendingCount }})</a></th><td>Entrate meno uscite residue</td><td class="text-end text-nowrap fw-bold">{{ \App\Support\Money::format($pendingImpact) }}</td></tr><tr class="table-success"><th colspan="2">Netto finale previsto</th><td class="text-end text-nowrap fw-bold">{{ \App\Support\Money::format($finalNet) }}</td></tr></tbody></table></div><p class="small text-secondary">Netto operativo = lordo − spese + saldo delle registrazioni pregresse. Netto finale previsto = netto operativo + impatto sospesi. I sospesi sono quelli sorti nel periodo, con residuo aggiornato a oggi; la previsione non è un saldo bancario né un bilancio fiscale. I saldi già riscossi/pagati sono nei movimenti e non vengono aggiunti una seconda volta.</p><p><a href="#delivery-details">Tariffe maturate sulle consegne del periodo: {{ \App\Support\Money::format($earned) }} · {{ $completedCount }} spedizioni</a></p><p class="small text-secondary">Il maturato è mostrato separatamente e non si somma agli incassi. I crediti sulle consegne entrano nella previsione solo quando registrati nel registro Sospesi.</p></section>
    <p class="small text-secondary my-4">Da incassare sulle consegne del periodo: <strong>{{ \App\Support\Money::format($outstanding) }}</strong> · Ordini annullati nel periodo: {{ $cancelledCount }}. Gli importi rappresentano le tariffe di consegna concordate.</p>
    <section class="mb-4" id="delivery-details"><h2 class="h4">Consegne e incassi</h2><h3 class="h5 mt-3">Incassi da registrare <span class="count-badge">{{ $orders->total() }}</span></h3>
    @forelse($orders as $order) @include('balance.receipt') @empty<p class="surface p-4 text-secondary">Nessun incasso da registrare nel periodo.</p>@endforelse{{ $orders->links() }}
    <h3 class="h5 mt-4">Incassi già registrati <span class="count-badge">{{ $recordedOrders->total() }}</span></h3>
    @forelse($recordedOrders as $order) @include('balance.receipt') @empty<p class="surface p-4 text-secondary">Nessun incasso già registrato nel periodo.</p>@endforelse{{ $recordedOrders->links() }}
    <h3 class="h5 mt-4" id="reversed-receipts">Storni <span class="count-badge">{{ $reversedOrders->total() }}</span></h3>
    <p class="small text-secondary">Questi incassi restano esclusi da quelli da registrare fino a un ripristino esplicito.</p>
    @forelse($reversedOrders as $order) @include('balance.receipt') @empty<p class="surface p-4 text-secondary">Nessuno storno nel periodo.</p>@endforelse{{ $reversedOrders->links() }}</section>
    <section id="expense-details"><header class="section-heading"><div><span class="eyebrow">SPESE</span><h2 class="h4 mb-0">Registra spesa</h2></div><x-ui.icon-button action="add" label="Registra spesa" data-dialog-open="expense-create" aria-controls="expense-create" aria-haspopup="dialog" /></header>@forelse($expenses as $expense)<article class="surface p-3 mb-3"><div class="d-flex justify-content-between flex-wrap gap-3"><div><strong>{{ $expense->description }}</strong>@if($expense->pendingSettlement && auth()->user()->role===\App\UserRole::Admin)<a class="small d-block" href="{{ route('pending.index',['id'=>$expense->pendingSettlement->pending_account_id]) }}">Saldo sospeso #{{ $expense->pendingSettlement->pending_account_id }}</a>@endif
@if(auth()->user()->role===\App\UserRole::Admin)<a class="small d-block" href="{{ route('audits.index',['type'=>'expenses','id'=>$expense->id]) }}">Storico modifiche</a>@endif<div class="small text-secondary">{{ $expense->spent_on->format('d/m/Y') }} · {{ $expense->user->name }}</div><span>{{ \App\Support\Money::format($expense->amount_cents) }} {{ $expense->voided_at ? '· Annullata' : '' }}</span></div>@unless($expense->voided_at || $expense->pending_settlement_id)<div class="row-actions"><x-ui.action-dialog :id="'expense-edit-'.$expense->id" title="Modifica spesa" :description="$expense->description"><form method="post" action="{{ route('expenses.update',$expense) }}" data-financial-form class="form-stack mt-3">@csrf @method('patch')<input type="hidden" name="version" value="{{ $expense->version }}"><x-ui.field name="description" :id="'expense-description-'.$expense->id" label="Descrizione" :value="$expense->description" required/><x-ui.field name="amount" :id="'expense-amount-'.$expense->id" label="Importo (€)" :value="number_format($expense->amount_cents/100,2,'.','')" required/><x-ui.field name="spent_on" :id="'expense-date-'.$expense->id" label="Data" type="date" :value="$expense->spent_on->toDateString()" required/><x-ui.icon-button action="edit" label="Salva modifica" type="submit" /></form></x-ui.action-dialog><form method="post" action="{{ route('expenses.destroy', $expense) }}" data-confirm="Annulla spesa" data-confirm-name="{{ $expense->description }}" class="m-0">@csrf @method('delete')<x-ui.icon-button action="delete" label="Annulla registrazione" type="submit" /></form></div>@endunless</div></article>@empty<div class="surface p-4 text-secondary">Nessuna spesa nel periodo.</div>@endforelse{{ $expenses->links() }}</section><x-ui.modal id="expense-create" title="Registra spesa"><div class="modal-content-area"><form method="post" action="{{ route('expenses.store') }}" data-financial-form class="form-stack mt-3">@csrf<input type="hidden" name="submission_key" value="{{ old('submission_key', (string) \Illuminate\Support\Str::uuid()) }}"><x-ui.field name="description" label="Descrizione" :value="old('description')" maxlength="200" required /><x-ui.field name="amount" label="Importo (€)" inputmode="decimal" :value="old('amount')" required /><x-ui.field name="spent_on" label="Data della spesa" type="date" :value="old('spent_on', now('Europe/Rome')->toDateString())" :max="now('Europe/Rome')->toDateString()" required /><x-ui.icon-button action="add" label="Registra spesa" type="submit" /></form></div></x-ui.modal>
    <section class="mt-4" id="cash-details"><h2 class="h4">Movimenti di cassa</h2>@if($generalReceipts)<p>Incassi da sospesi senza ordine: {{ \App\Support\Money::format($generalReceipts) }} · già inclusi nel totale.@if(auth()->user()->role===\App\UserRole::Admin) <a href="{{ route('pending.index') }}">Apri il registro</a>@endif</p>@endif<p class="small text-secondary">Registrazioni e storni, ordinati per data di inserimento.</p>@forelse($payments as $payment)<article class="surface p-3 mb-2"><div class="d-flex justify-content-between gap-3 flex-wrap"><div><a class="small text-break" href="{{ route('orders.show', $payment->order_id) }}">{{ $payment->order->reference }}</a><p class="mb-1">{{ $payment->note }}</p>@if($payment->method)<span class="small d-block">{{ \App\Support\PaymentMethod::Labels[$payment->method] ?? $payment->method }}</span>@endif<span class="small text-secondary">{{ $payment->created_at->timezone('Europe/Rome')->format('d/m/Y H:i') }} · {{ $payment->user->name }}</span></div><x-ui.signed-money :amount="$payment->amount_cents" /></div></article>@empty<p class="text-secondary">Nessun movimento registrato.</p>@endforelse{{ $payments->links() }}</section>
@include('balance.details')
</x-app-layout>
