<x-app-layout title="Centro operativo">
    <header class="dashboard-heading"><div><span class="eyebrow">OPERATIVITÀ · OGGI</span><h1>Ogni consegna,<br>sotto controllo<span class="brand-accent">.</span></h1><p>{{ $greeting }}, {{ auth()->user()->name }}. Ecco le priorità della giornata.</p></div><div class="date-chip"><x-ui.icon name="calendar3" />{{ $today }}</div></header>
    <section class="metrics-grid" data-live-region="metrics" aria-label="Riepilogo della giornata">@foreach($metrics as $metric)<x-dashboard.metric :metric="$metric" />@endforeach</section>
    <div class="operations-grid">
        <x-orders.live-map fleet />
        <div class="operations-stack">
            <section class="surface operations-section" data-live-region="incoming"><header><h2>Da prendere in carico</h2><x-ui.icon-button action="add" href="{{ route('orders.create') }}" label="Nuova richiesta" /></header><div class="dispatch-list">@forelse($requests as $order)<a class="dispatch-row" href="{{ route('orders.show', $order) }}"><div><span class="data-label">Cliente / negozio</span><strong>{{ $order->displayName() }}</strong><small>Percorso: {{ $order->pickup_city }} → {{ $order->delivery_city }}</small><span class="data-label mt-2">Nome destinatario</span><x-orders.recipient-name :name="$order->recipient_name" :risk="$recipientRisks[$order->id] ?? ['count'=>0,'last_at'=>null]" /></div><x-ui.status-badge class="status-pill tone-{{ $order->status->tone() }}">{{ $order->status->label() }}</x-ui.status-badge></a>@empty<p class="text-secondary">Nessuna richiesta in attesa.</p>@endforelse</div><a href="{{ route('orders.incoming') }}">Tutte le richieste →</a></section>
            <section class="surface operations-section" data-live-region="shipments"><header><h2>Prossime consegne</h2><x-ui.icon name="truck" /></header>@forelse($shipments as $order)<a class="dispatch-row" href="{{ route('orders.show', $order) }}"><div><span class="data-label mt-2">Nome destinatario</span><x-orders.recipient-name :name="$order->recipient_name" :risk="$recipientRisks[$order->id] ?? ['count'=>0,'last_at'=>null]" tag="strong" /><small>Località: {{ $order->delivery_city }}</small><small>Cliente / negozio: {{ $order->displayName() }}</small></div><x-ui.status-badge class="status-pill tone-{{ $order->status->tone() }}">{{ $order->status->label() }}</x-ui.status-badge></a>@empty<p class="text-secondary">Nessuna spedizione in corso.</p>@endforelse<a href="{{ route('orders.in-progress') }}">Apri le spedizioni →</a></section>
        </div>
    </div>
    <nav class="quick-links" aria-label="Accessi operativi"><a href="{{ route('pickups.index') }}"><x-ui.icon name="calendar2-week" /> Pianifica ritiri</a><a href="{{ route('tracking.index') }}"><x-ui.icon name="geo-alt" /> Mappa live</a><a href="{{ route('stores.index') }}"><x-ui.icon name="bar-chart" /> Statistiche clienti</a><a href="{{ route('reports.index') }}"><x-ui.icon name="file-earmark-bar-graph" /> Resoconti</a></nav>
</x-app-layout>
