<x-app-layout title="Dashboard">
    <header class="dashboard-heading"><div><span class="eyebrow">OGNI GIORNO, PIÙ VICINI</span><h1>{{ $greeting }}, {{ auth()->user()->name }}<span class="brand-accent">.</span></h1><p class="text-secondary mb-0">Richieste da prendere in carico, ritiri e consegne da completare.</p></div><div class="date-chip"><x-ui.icon name="calendar3" />{{ $today }}</div></header>
    <section class="metrics-grid mt-4" data-live-region="metrics" aria-label="Riepilogo della giornata">@foreach($metrics as $metric)<x-dashboard.metric :metric="$metric" />@endforeach</section>
    <nav class="quick-links" aria-label="Accessi operativi"><a href="{{ route('orders.incoming') }}"><x-ui.icon name="inbox"/> Da prendere in carico</a><a href="{{ route('orders.in-progress') }}"><x-ui.icon name="truck"/> Consegne in corso</a><a href="{{ route('pickups.index') }}"><x-ui.icon name="calendar2-week"/> Agenda ritiri</a><a href="{{ route('stores.index') }}"><x-ui.icon name="bar-chart"/> Statistiche</a></nav>
    <div class="d-flex justify-content-between align-items-center gap-3 flex-wrap my-4"><h2 class="h4 mb-0">Richieste recenti</h2><x-ui.icon-button action="add" href="{{ route('orders.create') }}" label="Nuova richiesta" /></div>
    <div class="row g-4"><section class="col-xl-7" data-live-region="incoming" aria-label="Richieste recenti">@forelse($requests as $order)<x-orders.card :recipient-risk="$recipientRisks[$order->id] ?? ['count' => 0, 'last_at' => null]" :order="$order" />@empty<div class="surface p-4"><h3 class="h5">Nessuna richiesta in attesa</h3><p class="text-secondary mb-0">Le nuove richieste compariranno qui.</p></div>@endforelse<a class="btn btn-outline-primary mt-2" href="{{ route('orders.incoming') }}">Tutti gli ordini in entrata</a></section>
    <section class="col-xl-5" data-live-region="shipments" aria-label="Spedizioni in corso"><div class="surface p-4"><h2 class="h5 mb-4">Spedizioni in corso</h2>@forelse($shipments as $order)<article class="border-bottom pb-3 mb-3"><a class="fw-semibold" href="{{ route('orders.show', $order) }}">{{ $order->displayName() }}</a><p class="small text-secondary my-1">{{ $order->pickup_city }} → {{ $order->delivery_city }}</p><p class="small">{{ $order->recipient_name }}<x-orders.recipient-risk :risk="$recipientRisks[$order->id] ?? ['count' => 0, 'last_at' => null]" /></p><span class="status-pill tone-{{ $order->status->tone() }}">{{ $order->status->label() }}</span></article>@empty<p class="text-secondary">Nessuna spedizione in corso.</p>@endforelse<a href="{{ route('orders.in-progress') }}">Apri le spedizioni <x-ui.icon name="arrow-right" /></a></div></section></div>
    <footer class="page-footer">EA-Express <span>Consegne locali, attenzione a ogni dettaglio.</span></footer>
</x-app-layout>
