@props(['title'])
<header class="app-header">
    <div class="d-flex align-items-center gap-3 min-width-0"><button type="button" class="icon-button d-lg-none" data-bs-toggle="offcanvas" data-bs-target="#app-navigation" aria-controls="app-navigation" aria-label="Apri menu"><x-ui.icon name="list" /></button><span class="header-title">{{ $title }}</span><span class="header-divider d-none d-md-block"></span><span class="small text-secondary d-none d-md-block">Il tuo spazio operativo</span></div>
    <div class="d-flex align-items-center gap-2 gap-md-3">
        <button type="button" class="sound-toggle" data-sound-toggle aria-pressed="false" aria-label="Attiva suoni notifiche"><x-ui.icon name="volume-mute" /><span>Attiva suoni</span></button>
        <div class="dropdown"><button type="button" class="icon-button" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Apri notifiche"><x-ui.icon name="bell" /><span class="notification-dot" data-notification-dot @if(!$unreadNotifications) hidden @endif aria-label="{{ $unreadNotifications }} notifiche da leggere"></span></button><div class="dropdown-menu dropdown-menu-end notification-menu p-3"><h2 class="h6">Notifiche</h2><p class="small text-secondary mb-0" data-notification-count>{{ $unreadNotifications ? $unreadNotifications . ' aggiornamenti da leggere.' : 'Nessun nuovo aggiornamento.' }}</p><a class="btn btn-outline-primary btn-sm mt-3" href="{{ route('notifications.index') }}">Tutte le notifiche</a></div></div>
        <div class="dropdown"><button type="button" class="account-button" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Apri menu account"><span class="avatar">{{ mb_strtoupper(mb_substr(auth()->user()->name, 0, 1)) }}</span><span class="account-name d-none d-md-block">{{ auth()->user()->name }}<small>Area rider</small></span><x-ui.icon name="chevron-down" class="d-none d-md-block" /></button>
            <div class="dropdown-menu dropdown-menu-end p-2"><a class="dropdown-item" href="{{ route('profile.edit') }}"><x-ui.icon name="person" class="me-2" />Il mio profilo</a><hr class="dropdown-divider"><form action="{{ route('logout') }}" method="post">@csrf<button type="submit" class="dropdown-item text-danger"><x-ui.icon name="box-arrow-right" class="me-2" />Esci</button></form></div>
        </div>
    </div>
</header>
