@props(['order', 'transitions'])
@php
    $exceptions = [\App\OrderStatus::Rejected, \App\OrderStatus::Cancelled, \App\OrderStatus::DeliveryIssue, \App\OrderStatus::DeliveryAttempted];
    $primary = $order->status === \App\OrderStatus::Accepted ? \App\OrderStatus::RiderArriving : collect($transitions)->first(fn ($status) => !in_array($status, $exceptions));
    $alternatives = collect($transitions)->reject(fn ($status) => $status === $primary);
@endphp
<section class="surface workflow-panel mb-4" id="next-action"><div class="workflow-heading"><span class="workflow-icon"><x-ui.icon name="signpost-split" /></span><div><span class="eyebrow">IL PROSSIMO PASSO</span><h2 class="h5 mb-0">{{ $primary ? $primary->actionLabel() : 'Gestisci l’imprevisto' }}</h2></div></div>
<p class="small text-secondary">Stato attuale: <strong>{{ $order->status->label() }}</strong>. {{ $order->status === \App\OrderStatus::Received ? 'Controlla percorso e orari, poi indica il costo della spedizione per assegnarla a te.' : 'Conferma il passaggio solo dopo aver effettuato l’operazione.' }}</p>
@if($primary)<form method="post" action="{{ route('orders.update', $order) }}" class="form-stack">@csrf @method('patch')<input type="hidden" name="version" value="{{ $order->version }}"><input type="hidden" name="status" value="{{ $primary->value }}">
@if($primary === \App\OrderStatus::Accepted)<x-ui.field name="price" label="Costo spedizione (€)" inputmode="decimal" :value="old('price')" placeholder="8,50" help="Compenso per il servizio, distinto dal valore della merce." required />@endif
@if($primary === \App\OrderStatus::Rescheduled)<x-ui.field name="estimated_at" label="Nuova previsione" type="datetime-local" :value="old('estimated_at')" required /><x-ui.field name="note" label="Motivo della riprogrammazione" :value="old('note')" required maxlength="2000" />@else<details class="optional-fields"><summary>Aggiungi un aggiornamento al cliente</summary><label for="public_note" class="form-label mt-2">Messaggio visibile nel tracking</label><textarea id="public_note" name="public_note" class="form-control" maxlength="500" rows="2">{{ old('public_note') }}</textarea><label for="primary-note" class="form-label mt-2">Nota interna (facoltativa)</label><textarea id="primary-note" name="note" class="form-control" rows="2" maxlength="2000">{{ old('note') }}</textarea></details>@endif
<button class="btn {{ $primary === \App\OrderStatus::Delivered ? 'btn-success' : 'btn-primary' }}"><x-ui.icon name="check2-circle" /> {{ $primary->actionLabel() }}</button></form>@endif
@if($alternatives->isNotEmpty())<details class="workflow-alternatives" @if(old('status') && $alternatives->contains(fn ($status) => $status->value === old('status'))) open @endif><summary>Altre azioni e imprevisti <x-ui.icon name="chevron-down" /></summary><div class="alternative-actions">@foreach($alternatives as $next)<details @if(old('status') === $next->value) open @endif><summary>{{ $next->actionLabel() }}</summary><form method="post" action="{{ route('orders.update', $order) }}" class="form-stack mt-2">@csrf @method('patch')<input type="hidden" name="version" value="{{ $order->version }}"><input type="hidden" name="status" value="{{ $next->value }}">@if(in_array($next, $exceptions))<x-ui.field :id="'note-'.$next->value" name="note" label="Motivo" :value="old('status') === $next->value ? old('note') : ''" maxlength="2000" required />@endif<button class="btn {{ in_array($next, $exceptions) ? 'btn-outline-danger' : 'btn-outline-primary' }} btn-sm">{{ $next->actionLabel() }}</button></form></details>@endforeach</div></details>@endif
</section>
