<x-app-layout title="Impostazioni"><header class="mb-4"><span class="eyebrow">IL TUO SPAZIO</span><h1>Impostazioni</h1><p class="text-secondary">Personalizza gli aggiornamenti che ricevi durante il lavoro.</p></header>@can('viewAny', \App\Models\User::class)<section class="surface p-4 mb-4 d-flex justify-content-between align-items-center flex-wrap gap-3"><div><h2 class="h5">Gestione profili</h2><p class="text-secondary mb-0">Crea account rider e gestisci gli accessi.</p></div><a class="btn btn-primary" href="{{ route('users.index') }}"><x-ui.icon name="people" /> Gestione utenti</a></section>@endcan
<div class="row g-4"><section class="col-xl-7"><form method="post" action="{{ route('settings.update') }}" class="surface p-4 form-stack">@csrf @method('patch')<h2 class="h5">Notifiche nel gestionale</h2>@foreach(['notify_orders'=>'Aggiornamenti sugli ordini', 'notify_messages'=>'Nuovi messaggi dei clienti e del team'] as $field=>$label)<input type="hidden" name="{{ $field }}" value="0"><label class="form-check form-switch"><input class="form-check-input" type="checkbox" role="switch" name="{{ $field }}" value="1" @checked(old($field, $user->$field))><span class="form-check-label">{{ $label }}</span></label>@endforeach<p class="small text-secondary">Queste preferenze controllano gli avvisi nella campanella. Ordini e conversazioni restano consultabili anche quando gli avvisi sono disattivati.</p><x-ui.icon-button action="edit" label="Salva preferenze" type="submit" /></form></section><aside class="col-xl-5"><div class="surface p-4"><header class="card-heading"><h2 class="h5">Sicurezza dell’account</h2><div class="card-actions"><x-ui.icon-button action="edit" :href="route('profile.edit')" label="Modifica profilo e password" /></div></header><x-ui.status-badge class="status-pill tone-green"><x-ui.icon name="shield-check" /> {{ $user->role === \App\UserRole::Admin ? 'Amministratore' : ($user->phone_verified_at ? 'Cellulare verificato' : 'Accesso sviluppo senza OTP') }}</x-ui.status-badge><p class="small mt-3 text-break">Email: {{ $user->email }}</p><p class="small text-secondary">L’accesso al gestionale è riservato agli operatori abilitati. Per creare o disabilitare un account, contatta il responsabile.</p></div><div class="surface p-4 mt-4"><h2 class="h5">Preferenze operative</h2><dl class="mb-0"><dt>Lingua</dt><dd>Italiano</dd><dt>Fuso orario</dt><dd>Europe/Rome</dd><dt>Valuta</dt><dd class="mb-0">Euro (€)</dd></dl></div></aside></div>
@if($accounting)
<section class="surface workspace-section mt-4"><header class="section-heading"><div><span class="eyebrow">INTEGRITÀ CONTABILE</span><h2>Chiusura delle registrazioni</h2></div><x-ui.icon-button action="history" :href="route('audits.index',['type'=>'accounting_controls','id'=>1])" label="Storico chiusure" /></header>
<p>{{ $accounting->closed_through ? 'Registrazioni chiuse fino al '.$accounting->closed_through->format('d/m/Y') : 'Nessun periodo chiuso.' }}</p>
<p class="small text-secondary">La chiusura impedisce inserimenti retrodatati, modifiche e annullamenti di pagamenti, spese e movimenti nelle date protette. Una riapertura richiede una motivazione e resta nello storico. Gli storni registrati oggi non riscrivono gli incassi dei periodi chiusi.</p>
<x-ui.action-dialog id="accounting-period" action="edit" title="Gestisci chiusura contabile" :open="old('accounting_form') && $errors->any()" text>
<form method="post" action="{{ route('settings.accounting') }}" class="form-stack">@csrf @method('patch')<input type="hidden" name="version" value="{{ $accounting->version }}"><input type="hidden" name="accounting_form" value="1">
<div><label for="accounting-action" class="form-label">Operazione</label><select class="form-select" id="accounting-action" name="action"><option value="close">Chiudi fino alla data</option>@if($accounting->closed_through)<option value="reopen" @selected(old('action')==='reopen')>Riapri dopo la data</option>@endif</select></div>
<x-ui.field name="closed_through" label="Ultima data che resterà chiusa" type="date" :value="old('closed_through')" :max="now('Europe/Rome')->subDay()->toDateString()" help="Obbligatoria per chiudere. In riapertura, lascia vuoto per riaprire tutti i periodi." />
<x-ui.field id="accounting-reason" name="reason" label="Motivazione" :value="old('reason')" maxlength="500" required />
<x-ui.icon-button action="edit" label="Conferma aggiornamento" type="submit" data-confirm="Aggiorna chiusura contabile" data-confirm-name="periodi contabili" text />
</form></x-ui.action-dialog>
</section>
<section class="surface workspace-section mt-4"><header class="section-heading"><div><span class="eyebrow">CONTINUITÀ OPERATIVA</span><h2>Backup e scheduler</h2></div><x-ui.status-badge class="status-pill {{ $backup['enabled'] && $backup['backup_fresh'] && $backup['restore_fresh'] && $backup['scheduler_alive'] ? 'tone-green' : 'tone-orange' }}">{{ $backup['enabled'] && $backup['backup_fresh'] && $backup['restore_fresh'] && $backup['scheduler_alive'] ? 'Verificato' : 'Da verificare' }}</x-ui.status-badge></header>
<dl class="field-grid"><div><dt>Modalità configurata</dt><dd>{{ $backup['local'] ? 'Copia cifrata locale' : 'Copia cifrata esterna' }} · {{ $backup['enabled'] ? 'Pianificazione abilitata' : 'Pianificazione disabilitata' }}</dd></div><div><dt>Scheduler</dt><dd>{{ $backup['scheduler_alive'] ? 'Esecuzione rilevata negli ultimi 5 minuti' : 'Nessuna esecuzione recente rilevata' }}</dd></div><div><dt>Ultimo backup riuscito</dt><dd>{{ $backup['backup_at'] ?? 'Non disponibile' }} · {{ $backup['backup_fresh'] ? 'Recente' : 'Assente o scaduto' }}</dd></div><div><dt>Ultimo ripristino verificato</dt><dd>{{ $backup['verified_at'] ?? 'Non disponibile' }} · {{ $backup['restore_fresh'] ? 'Recente' : 'Assente o scaduto' }}</dd></div></dl>
<p class="small text-secondary mb-0">Backup alle 02:00, verifica di ripristino domenica alle 04:00 e controllo giornaliero alle 06:00, in ora italiana. {{ $backup['local'] ? 'La copia locale non protegge dalla perdita del computer o del disco: serve anche una destinazione esterna.' : 'La destinazione esterna deve essere disponibile al momento del backup.' }} L’attivazione sul server richiede lo scheduler di sistema. Questa pagina mostra gli esiti registrati, non esegue ripristini sul database del gestionale.</p>
</section>
@endif
</x-app-layout>
