<x-app-layout title="Nuova richiesta">
    <header class="mb-4"><span class="eyebrow">ORDINI</span><h1>Nuova richiesta</h1><p class="text-secondary">Inserisci la spedizione per conto del negozio o del cliente.</p></header>
    <form method="post" action="{{ route('orders.store') }}" class="surface p-3 p-md-4 form-stack">@csrf
        <section class="form-section"><h2>1. Mittente</h2><fieldset class="sender-choice"><legend>Chi spedisce?</legend><label><input type="radio" name="sender_type" value="business" @checked(old('sender_type', 'business') === 'business')> Attività commerciale</label><label><input type="radio" name="sender_type" value="private" @checked(old('sender_type') === 'private')> Privato</label></fieldset><div class="field-grid"><x-ui.field name="store_name" :label="old('sender_type') === 'private' ? 'Nome e cognome del mittente' : 'Nome attività'" :value="old('store_name')" maxlength="150" required /><x-ui.field name="contact_email" label="Email mittente (facoltativa)" type="email" :value="old('contact_email')" /></div><div class="field-grid identity-business" data-business-fields @if(old('sender_type') === 'private') hidden @endif><x-ui.field name="business_type" label="Tipologia attività" :value="old('business_type')" maxlength="100" list="business-types" placeholder="Scegli o scrivi liberamente"/><datalist id="business-types"><option value="Abbigliamento"><option value="Fiorista"><option value="Artigianato"><option value="E-commerce"><option value="Alimentari"></datalist><x-ui.field name="business_description" label="Di cosa si occupa? (facoltativo)" :value="old('business_description')" maxlength="500" /></div></section>
        <section class="form-section"><h2>2. Percorso e destinatario</h2><div class="field-grid"><x-ui.field name="pickup_address" label="Indirizzo di ritiro" :value="old('pickup_address')" required/><x-ui.field name="pickup_city" label="Comune di ritiro" :value="old('pickup_city')" required/></div><div class="field-grid mt-3"><x-ui.field name="recipient_name" label="Nome destinatario" :value="old('recipient_name')" required/><x-ui.field name="recipient_phone" label="Telefono destinatario" type="tel" :value="old('recipient_phone')" required/></div><div class="field-grid mt-3"><x-ui.field name="delivery_address" label="Indirizzo di consegna" :value="old('delivery_address')" required/><x-ui.field name="delivery_city" label="Comune di consegna" :value="old('delivery_city')" required/></div></section>
        <section class="form-section"><h2>3. Quando ritirare</h2><div class="field-grid"><x-ui.field name="pickup_date" label="Data del ritiro" type="date" :value="old('pickup_date', now('Europe/Rome')->toDateString())" :min="now('Europe/Rome')->toDateString()" required/><div class="field-grid time-range"><x-ui.field name="pickup_from" label="Dalle" type="time" :value="old('pickup_from', '09:00')" required/><x-ui.field name="pickup_to" label="Alle" type="time" :value="old('pickup_to', '12:00')" required/></div></div><div class="mt-3"><x-ui.field name="delivery_window" label="Preferenza oraria di consegna (facoltativa)" :value="old('delivery_window')" maxlength="150"/></div></section>
        <section class="form-section"><h2>4. Pacco e indicazioni</h2><div class="field-grid"><x-ui.field name="parcel_count" label="pacchi" type="number" min="1" max="100" :value="old('parcel_count', 1)" required/><x-ui.field name="parcel_value" label="Valore merce (€)" inputmode="decimal" :value="old('parcel_value')" placeholder="0,00" help="Non è il costo della spedizione."/><div class="select-field"><label for="category" class="form-label">Contenuto</label><select id="category" class="form-select" name="category">@foreach(\App\Support\OrderContent::Categories as $value=>$label)<option value="{{ $value }}" @selected(old('category', 'other') === $value)>{{ $label }}</option>@endforeach</select></div><div class="select-field"><label for="urgency" class="form-label">Priorità</label><select id="urgency" class="form-select" name="urgency"><option value="standard">Standard</option><option value="urgent" @selected(old('urgency') === 'urgent')>Urgente</option></select></div></div><x-ui.field name="content_description" label="Descrizione del contenuto (facoltativa)" maxlength="255" :value="old('content_description')"/><div data-package-fields="{{ json_encode(old('packages', [])) }}"></div><div class="mt-3"><label for="notes" class="form-label">Note riservate al rider</label><textarea class="form-control" name="notes" id="notes" rows="2" maxlength="2000">{{ old('notes') }}</textarea></div></section>
        <div class="d-flex flex-wrap gap-2"><button class="btn btn-primary"><x-ui.icon name="plus-lg" /> Crea richiesta</button><a class="btn btn-outline-secondary" href="{{ route('orders.incoming') }}">Annulla</a></div>
    </form>
</x-app-layout>
