<x-app-layout title="Nuova richiesta">
    <header class="mb-4"><span class="eyebrow">ORDINI</span><h1>Nuova richiesta</h1><p class="text-secondary">Inserisci la spedizione per conto del negozio o del cliente.</p></header>
    <form method="post" action="{{ route('orders.store') }}" class="surface p-3 p-md-4 form-stack">@csrf
        <h2 class="h5">Cliente e destinatario</h2><div class="row g-3"><div class="col-md-6"><x-ui.field name="store_name" label="Negozio / cliente" :value="old('store_name')" maxlength="150" required /></div><div class="col-md-6"><x-ui.field name="contact_email" label="Email del negozio (facoltativa)" type="email" :value="old('contact_email')" /></div><div class="col-md-6"><x-ui.field name="recipient_name" label="Nome destinatario" :value="old('recipient_name')" required /></div><div class="col-md-6"><x-ui.field name="recipient_phone" label="Telefono destinatario" type="tel" :value="old('recipient_phone')" required /></div></div>
        <h2 class="h5 mt-4">Percorso e orari</h2><div class="row g-3">@foreach(['pickup_address' => 'Indirizzo di ritiro', 'pickup_city' => 'Comune di ritiro', 'delivery_address' => 'Indirizzo di consegna', 'delivery_city' => 'Comune di consegna'] as $name => $label)<div class="col-md-6"><x-ui.field :name="$name" :label="$label" :value="old($name)" required /></div>@endforeach<div class="col-md-4"><x-ui.field name="pickup_date" label="Data del ritiro" type="date" :value="old('pickup_date', now('Europe/Rome')->toDateString())" :min="now('Europe/Rome')->toDateString()" required /></div><div class="col-md-4"><x-ui.field name="pickup_from" label="Ritiro dalle" type="time" :value="old('pickup_from', '09:00')" required /></div><div class="col-md-4"><x-ui.field name="pickup_to" label="Ritiro entro le" type="time" :value="old('pickup_to', '12:00')" required /></div><div class="col-12"><x-ui.field name="delivery_window" label="Preferenza oraria di consegna (facoltativa)" :value="old('delivery_window')" maxlength="150" /></div></div>
        <h2 class="h5 mt-4">Colli e indicazioni</h2><div class="row g-3"><div class="col-md-4"><x-ui.field name="parcel_count" label="Numero colli" type="number" min="1" max="100" :value="old('parcel_count', 1)" required /></div><div class="col-md-4"><label for="category" class="form-label">Categoria</label><select class="form-select" name="category" id="category">@foreach(['clothing'=>'Abbigliamento', 'documents'=>'Documenti', 'other'=>'Altro'] as $value=>$label)<option value="{{ $value }}" @selected(old('category') === $value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-4"><label for="urgency" class="form-label">Urgenza</label><select class="form-select" name="urgency" id="urgency"><option value="standard">Standard</option><option value="urgent" @selected(old('urgency') === 'urgent')>Urgente</option></select></div></div>
        <div><label for="notes" class="form-label">Note riservate al rider</label><textarea class="form-control" name="notes" id="notes" rows="3" maxlength="2000">{{ old('notes') }}</textarea></div>
        <div class="d-flex flex-wrap gap-2"><button class="btn btn-primary"><x-ui.icon name="plus-lg" /> Crea richiesta</button><a class="btn btn-outline-secondary" href="{{ route('orders.incoming') }}">Annulla</a></div>
    </form>
</x-app-layout>
