<x-app-layout :title="$title">
    <header class="dashboard-heading mb-4"><div><span class="eyebrow">CENTRO OPERATIVO</span><h1>{{ $title }} @if($section==='orders.in-progress')<span data-live-region="current-count"><span class="badge rounded-pill text-bg-primary fs-6 align-middle" aria-label="Spedizioni in corso">{{ $currentCount }}</span></span>@endif</h1><p class="text-secondary mb-0">{{ $section === 'orders.history' ? 'Consulta gli ordini chiusi degli ultimi 12 mesi.' : 'Organizza ritiri e consegne, una richiesta alla volta.' }}</p></div><a class="btn btn-primary create-button" href="{{ route('orders.create') }}" aria-label="Nuova richiesta" title="Nuova richiesta"><span aria-hidden="true">+</span></a></header>
    <form method="get" class="surface p-3 mb-4"><div class="row g-3"><div class="col-md-4"><x-ui.field name="q" label="Cliente o riferimento" :value="request('q')" /></div><div class="col-md-4"><x-ui.field name="zone" label="Zona di consegna" :value="request('zone')" /></div><div class="col-md-4"><label class="form-label" for="urgency">Urgenza</label><select id="urgency" name="urgency" class="form-select"><option value="">Tutte</option><option value="standard" @selected(request('urgency') === 'standard')>Standard</option><option value="urgent" @selected(request('urgency') === 'urgent')>Urgente</option></select></div>
    @if($section === 'orders.history')<div class="col-md-4"><x-ui.field name="from" label="Dal" type="date" :value="request('from')" /></div><div class="col-md-4"><x-ui.field name="to" label="Al" type="date" :value="request('to')" /></div><div class="col-md-4"><label class="form-label" for="status">Stato</label><select id="status" name="status" class="form-select"><option value="">Tutti</option>@foreach(\App\OrderStatus::closed() as $state)<option value="{{ $state }}" @selected(request('status') === $state)>{{ \App\OrderStatus::from($state)->label() }}</option>@endforeach</select></div>@endif
    <div class="col-md-4"><label for="sender_type" class="form-label">Tipo mittente</label><select name="sender_type" id="sender_type" class="form-select"><option value="">Tutti</option>@foreach(['business'=>'Attività commerciale','private'=>'Privato','online_shop'=>'Shop online'] as $v=>$label)<option value="{{ $v }}" @selected(request('sender_type')===$v)>{{ $label }}</option>@endforeach</select></div></div><div class="d-flex gap-2 mt-3"><button class="btn btn-primary">Filtra</button><a class="btn btn-outline-secondary" href="{{ route($section) }}">Azzera</a></div></form>
    <div data-live-region="orders">@if($section==='orders.in-progress')<div class="surface p-3 mb-4 d-flex flex-wrap gap-3 align-items-center"><strong>{{ $orders->total() }} risultati filtrati</strong><a class="btn btn-outline-primary" target="_blank" rel="noopener" href="{{ route('labels.index',[...request()->only(['q','zone','status','urgency','sender_type','from','to']),'scope'=>'filtered']) }}"><x-ui.icon name="printer"/> Stampa risultati filtrati ({{ $orders->total() }})</a><a class="btn btn-primary" target="_blank" rel="noopener" href="{{ route('labels.index',['scope'=>'all']) }}"><x-ui.icon name="printer"/> Stampa tutte le spedizioni in corso ({{ $currentCount }})</a><small class="text-secondary">Un documento A6 · un’etichetta per spedizione · tutte le pagine dei risultati</small></div>@endif
@forelse($orders as $order)<x-orders.card :order="$order" />@empty<div class="surface p-5 text-center"><x-ui.icon name="inbox" class="display-6 text-secondary" /><h2 class="h5 mt-3">Nessun ordine trovato</h2><p class="text-secondary mb-0">Le richieste compariranno qui. Puoi crearne una o modificare i filtri.</p></div>@endforelse
    <div class="mt-4">{{ $orders->links() }}</div>
</div></x-app-layout>
