<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Etichette EA Express</title>@vite(['resources/css/app.css', 'resources/js/labels.js'])
<style>
body{font:12px Arial,sans-serif;margin:0;background:#eee;color:#111}.tools{padding:20px;text-align:center}.label{box-sizing:border-box;width:105mm;min-height:148mm;padding:6mm;background:white;margin:12px auto;overflow-wrap:anywhere;border:1px solid #bbb}.label-brand{display:flex;align-items:center;justify-content:space-between;border-bottom:2px solid #111;padding-bottom:6px}.label-brand img{width:28mm;height:15mm}.reference{font:700 12px monospace;margin:8px 0;overflow-wrap:anywhere}.section{border-top:1px solid #aaa;padding-top:7px;margin-top:7px}.label h2{font-size:10px;text-transform:uppercase;letter-spacing:.06em;margin:0 0 5px}.label dl{margin:0}.label dl div{display:flex;gap:5px;margin:3px 0;line-height:1.25}.label dt{font-size:10px;min-width:27mm;font-weight:600}.label dd{margin:0;min-width:0}.label .recipient{font-size:17px;font-weight:700}.fragile{font-size:18px;font-weight:900;border:2px solid;padding:3px;text-align:center;margin-top:8px}.label footer{font-size:9px;margin-top:8px}
@page{size:105mm 148mm;margin:0}@media print{body{background:white}.tools{display:none}.label{border:0;margin:0;min-height:148mm;break-after:page}.section{break-inside:avoid}.label:last-child{break-after:auto}}@media screen and (max-width:420px){.label{width:100%;min-height:0}}
</style></head><body><div class="tools"><x-ui.icon-button :action="$orders->count() > 1 ? 'print-multiple' : 'print'" :label="$orders->count() > 1 ? 'Stampa tutte le etichette' : 'Stampa etichetta'" data-print-labels/><p>{{ $orders->count() }} spedizioni · {{ $orders->sum('parcel_count') }} colli · formato A6</p></div>
@foreach($orders as $order)<article class="label">
<header class="label-brand"><img src="{{ asset('brand.svg') }}" alt="EA Express"><strong>COLLI: {{ $order->parcel_count }}</strong></header>
<div class="reference"><small>CODICE SPEDIZIONE</small><br>{{ $order->reference }}</div>
<section class="section"><h2>Destinatario</h2><dl><div><dt>Nome:</dt><dd class="recipient">{{ $order->recipient_name }}</dd></div><div><dt>Numero cellulare:</dt><dd>{{ $order->recipient_phone }}</dd></div><div><dt>Indirizzo consegna:</dt><dd>{{ $order->delivery_address }} {{ $order->delivery_street_number }}</dd></div><div><dt>Città:</dt><dd>{{ $order->delivery_city }}</dd></div><div><dt>CAP:</dt><dd>{{ $order->delivery_postal_code ?: 'Non indicato' }}</dd></div>@if($order->delivery_province)<div><dt>Provincia:</dt><dd>{{ $order->delivery_province }}</dd></div>@endif @if($order->delivery_region)<div><dt>Regione:</dt><dd>{{ $order->delivery_region }}</dd></div>@endif</dl></section>
<section class="section"><h2>Mittente / ritiro</h2><dl><div><dt>Nome:</dt><dd>{{ $order->store_name }}</dd></div><div><dt>Indirizzo ritiro:</dt><dd>{{ $order->pickup_address }} {{ $order->pickup_street_number }}</dd></div><div><dt>Città / CAP:</dt><dd>{{ $order->pickup_city }} · {{ $order->pickup_postal_code }}</dd></div><div><dt>Data / fascia ritiro:</dt><dd>{{ $order->pickup_date->format('d/m/Y') }} · {{ substr($order->pickup_from,0,5) }}–{{ substr($order->pickup_to,0,5) }}</dd></div></dl></section>
<section class="section"><h2>Informazioni operative</h2><dl><div><dt>Contenuto:</dt><dd>{{ \App\Support\OrderContent::label($order->category, $order->content_description) }}</dd></div><div><dt>Servizio:</dt><dd>{{ $order->shipping_type === 'external' ? 'Fuori regione' : 'Regionale' }}</dd></div>@if($order->carrier_name)<div><dt>Vettore:</dt><dd>{{ $order->carrier_name }}</dd></div>@endif @if($order->carrier_tracking)<div><dt>Tracking vettore:</dt><dd>{{ $order->carrier_tracking }}</dd></div>@endif @if($order->weight_kg)<div><dt>Peso totale:</dt><dd>{{ $order->weight_kg }} kg</dd></div>@endif</dl></section>
@if($order->package_type==='fragile')<div class="fragile">FRAGILE</div>@elseif($order->package_type==='other')<p><strong>Caratteristiche:</strong> {{ $order->package_description }}</p>@endif
<footer>Conservare il codice per identificare la spedizione.</footer></article>@endforeach</body></html>
