<x-app-layout title="Dettaglio ordine">
    <nav class="page-back" aria-label="Navigazione pagina"><x-ui.icon-button action="back" href="{{ route('orders.incoming') }}" label="Torna indietro" text /></nav><header class="page-heading"><div><span class="eyebrow text-break">{{ $order->reference }}</span><h1>{{ $order->displayName() }}</h1><p class="text-secondary mb-0">{{ $order->sender_type === 'private' ? 'Privato' : ($order->sender_type === 'online_shop' ? 'Shop online' : ($order->business_type ?: 'Attività commerciale')) }} · {{ $order->pickup_city }} → {{ $order->delivery_city }}</p></div></header>
    <div class="order-detail-layout" data-live-order="{{ $order->id }}">
        <section class="order-overview"><x-orders.card :order="$order" :action="false" /></section>
        <aside class="order-workflow"><x-orders.price :order="$order" />
            @can('update', $order)
                @if(count($transitions) && ($order->status !== \App\OrderStatus::Rejected || $order->recoverable()))
                    <x-orders.workflow :order="$order" :transitions="$transitions" />
                @elseif($order->status === \App\OrderStatus::Rejected)<div class="surface p-4"><h2 class="h6">Richiesta rifiutata</h2><p class="small text-secondary mb-0">La finestra di un’ora per recuperarla è scaduta.</p></div>
                @else<div class="surface p-4"><span class="status-pill tone-{{ $order->status->tone() }}">{{ $order->status->label() }}</span><p class="small text-secondary mt-3 mb-0">Non sono richieste altre operazioni su questa spedizione.</p></div>@endif
            @endcan
            <a class="btn btn-outline-primary mb-3" href="{{ route('messages.show', $order) }}"><x-ui.icon name="chat-dots" /> Invia messaggio</a>
        </aside>
        <section class="surface order-information p-4"><h2 class="h5 mb-3">Dati utili per la consegna</h2><dl class="operation-facts"><div><dt>Servizio</dt><dd>{{ $order->shipping_type === 'external' ? 'Fuori regione' : 'Regionale' }}</dd></div><div><dt>Provincia / Regione</dt><dd>{{ $order->delivery_province }} · {{ $order->delivery_region }}</dd></div><div><dt>Destinatario</dt><dd>{{ $order->recipient_name }}</dd></div><div><dt>Telefono destinatario</dt><dd>{{ $order->recipient_phone }}</dd></div><div><dt>Contatto mittente</dt><dd>{{ $order->contact_email ?: 'Non indicato' }}</dd></div><div><dt>Contenuto</dt><dd>{{ \App\Support\OrderContent::label($order->category, $order->content_description) }}</dd></div><div><dt>Incasso effettivo registrato</dt><dd>{{ \App\Support\Money::format((int) $order->payments_sum_amount_cents) }}</dd></div><div><dt>Tracking vettore</dt><dd>{{ $order->carrier_tracking ?: 'Non indicato' }}</dd></div><div><dt>Tariffa prevista</dt><dd>{{ \App\Support\Money::format($order->price_cents) }}</dd></div><div><dt>Valore merce dichiarato</dt><dd>{{ $order->parcel_value_cents === null ? 'Non dichiarato' : \App\Support\Money::format($order->parcel_value_cents) }}</dd></div><div><dt>Preferenza oraria di consegna</dt><dd>{{ $order->delivery_window ?: 'Nessuna preferenza' }}</dd></div><div><dt>Rider</dt><dd>{{ $order->rider?->name ?: 'Da assegnare' }}</dd></div></dl>
        @if($order->packages)<h3 class="h6 mt-4">Peso e dimensioni dei pacchi</h3><div class="package-summary">@foreach($order->packages as $package)<p class="small mb-2"><strong>Pacco {{ $loop->iteration }}</strong> · {{ $package['weight_kg'] }} kg · {{ $package['length_cm'] }} × {{ $package['width_cm'] }} × {{ $package['height_cm'] }} cm</p>@endforeach</div>@endif
        @if($order->business_description)<p class="small text-secondary">Attività: {{ $order->business_description }}</p>@endif
        @if($order->customer_notes)<div class="operational-note"><strong>Istruzioni del cliente</strong><p>{{ $order->customer_notes }}</p></div>@endif
        @if($order->notes)<div class="operational-note internal"><strong>Note interne · solo operatori</strong><p>{{ $order->notes }}</p></div>@endif
        @if($order->shipping_type === 'external' && !in_array($order->status->value, \App\OrderStatus::closed(), true))<details class="optional-fields mt-3"><summary>Dati del vettore (facoltativi)</summary><x-orders.carrier :order="$order" /></details>@endif<details class="optional-fields mt-3"><summary>Tracking del cliente</summary>@if($order->tracking_started_at)<p class="small text-secondary mt-2">Condividi questo collegamento solo con il cliente o il destinatario.</p><a class="btn btn-outline-primary btn-sm" href="{{ route('tracking.public', $order->tracking_token) }}">Apri tracking cliente <x-ui.icon name="arrow-up-right" /></a>@else<p class="small text-secondary mt-2 mb-0">Il tracking si attiva quando parti per il ritiro.</p>@endif</details>
        <p><strong>{{ $order->package_type==='fragile'?'FRAGILE':($order->package_type==='other'?$order->package_description:'Pacco standard') }}</strong></p><p>Ritiro: {{ $order->pickup_address }} {{ $order->pickup_street_number }}, {{ $order->pickup_postal_code }} {{ $order->pickup_city }}<br>Consegna: {{ $order->delivery_address }} {{ $order->delivery_street_number }}, {{ $order->delivery_postal_code }} {{ $order->delivery_city }}</p><x-ui.icon-button action="print" href="{{ route('labels.index',['ids'=>[$order->id]]) }}" label="Stampa etichetta" target="_blank" rel="noopener" />@if($canReschedulePickup)@can('update',$order)<div class="mt-3"><x-orders.pickup-schedule :order="$order" /></div>@endcan @endif<details class="mt-3"><summary>Origine del prezzo</summary><p class="mt-2">Tariffa iniziale: {{ \App\Support\Money::format($order->quoted_price_cents) }} · Tariffa applicata: {{ \App\Support\Money::format($order->price_cents) }}</p><p>Versione listino #{{ $order->shipping_rate_id ?? 'storica' }} · {{ $order->rate_snapshot['city'] ?? $order->delivery_city }} · {{ $order->rate_snapshot['source_reference'] ?? 'Fonte non registrata nello storico' }}</p>@if(auth()->user()->role===\App\UserRole::Admin)<a href="{{ route('audits.index',['type'=>'orders','id'=>$order->id]) }}">Storico economico dell’ordine</a>@endif</details>
        </section>
        <details class="surface order-history p-4"><summary class="fw-semibold">Cronologia della spedizione <span class="count-pill">{{ $events->total() }}</span></summary><ol class="tracking-timeline mt-3">@foreach($events as $event)<li><strong>{{ $event->schedule_change ? ($event->schedule_change['before'] ? 'Ritiro ripianificato' : 'Ritiro pianificato') : $event->status->label() }}</strong><div class="small text-secondary">{{ $event->created_at->timezone('Europe/Rome')->format('d/m/Y H:i') }} · {{ $event->user->name }}</div>@if($event->schedule_change)<div class="small mt-2">@if($event->schedule_change['before'])<span class="text-secondary">{{ \Illuminate\Support\Carbon::parse($event->schedule_change['before']['pickup_date'])->format('d/m/Y') }} · {{ $event->schedule_change['before']['pickup_from'] }}–{{ $event->schedule_change['before']['pickup_to'] }}</span> → @endif<strong>{{ \Illuminate\Support\Carbon::parse($event->schedule_change['after']['pickup_date'])->format('d/m/Y') }} · {{ $event->schedule_change['after']['pickup_from'] }}–{{ $event->schedule_change['after']['pickup_to'] }}</strong></div>@endif @if($event->note)<p class="mb-1 text-break">{{ $event->note }}</p>@endif @if($event->public_note)<p class="small mb-0 text-break">Pubblico: {{ $event->public_note }}</p>@endif</li>@endforeach</ol>{{ $events->links() }}</details>
    </div>
</x-app-layout>
