<x-app-layout title="Dettaglio ordine">
    <header class="mb-4"><a href="{{ route('orders.incoming') }}" class="btn btn-outline-secondary btn-sm mb-3"><x-ui.icon name="arrow-left" /> Ordini</a><span class="eyebrow text-break">{{ $order->reference }}</span><h1>{{ $order->store_name }}</h1><p class="text-secondary mb-0">{{ $order->sender_type === 'private' ? 'Privato' : ($order->business_type ?: 'Attività commerciale') }} · {{ $order->pickup_city }} → {{ $order->delivery_city }}</p></header>
    <div class="order-detail-layout" data-live-order="{{ $order->id }}">
        <section class="order-overview"><x-orders.card :order="$order" :action="false" /></section>
        <aside class="order-workflow">
            @can('update', $order)
                @if(count($transitions) && ($order->status !== \App\OrderStatus::Rejected || $order->recoverable()))
                    <x-orders.workflow :order="$order" :transitions="$transitions" />
                @elseif($order->status === \App\OrderStatus::Rejected)<div class="surface p-4"><h2 class="h6">Richiesta rifiutata</h2><p class="small text-secondary mb-0">La finestra di un’ora per recuperarla è scaduta.</p></div>
                @else<div class="surface p-4"><span class="status-pill tone-{{ $order->status->tone() }}">{{ $order->status->label() }}</span><p class="small text-secondary mt-3 mb-0">Non sono richieste altre operazioni su questa spedizione.</p></div>@endif
            @endcan
            <a class="btn btn-outline-primary mb-3" href="{{ route('messages.show', $order) }}"><x-ui.icon name="chat-dots" /> Conversazione con il cliente</a>
        </aside>
        <section class="surface order-information p-4"><h2 class="h5 mb-3">Dati utili per la consegna</h2><dl class="operation-facts"><div><dt>Destinatario</dt><dd>{{ $order->recipient_name }}</dd></div><div><dt>Telefono destinatario</dt><dd>{{ $order->recipient_phone }}</dd></div><div><dt>Contatto mittente</dt><dd>{{ $order->contact_email ?: 'Non indicato' }}</dd></div><div><dt>Contenuto</dt><dd>{{ ['clothing'=>'Abbigliamento','documents'=>'Documenti','other'=>'Altro'][$order->category] }}</dd></div><div><dt>Costo spedizione</dt><dd>{{ \App\Support\Money::format($order->price_cents) }}</dd></div><div><dt>Valore merce dichiarato</dt><dd>{{ $order->parcel_value_cents === null ? 'Non dichiarato' : \App\Support\Money::format($order->parcel_value_cents) }}</dd></div><div><dt>Preferenza oraria di consegna</dt><dd>{{ $order->delivery_window ?: 'Nessuna preferenza' }}</dd></div><div><dt>Rider</dt><dd>{{ $order->rider?->name ?: 'Da assegnare' }}</dd></div></dl>
        @if($order->packages)<h3 class="h6 mt-4">Peso e dimensioni dei pacchi</h3><div class="package-summary">@foreach($order->packages as $package)<p class="small mb-2"><strong>Pacco {{ $loop->iteration }}</strong> · {{ $package['weight_kg'] }} kg · {{ $package['length_cm'] }} × {{ $package['width_cm'] }} × {{ $package['height_cm'] }} cm</p>@endforeach</div>@endif
        @if($order->business_description)<p class="small text-secondary">Attività: {{ $order->business_description }}</p>@endif
        @if($order->customer_notes)<div class="operational-note"><strong>Istruzioni del cliente</strong><p>{{ $order->customer_notes }}</p></div>@endif
        @if($order->notes)<div class="operational-note internal"><strong>Note interne · solo operatori</strong><p>{{ $order->notes }}</p></div>@endif
        <details class="optional-fields mt-3"><summary>Tracking del cliente</summary>@if($order->tracking_started_at)<p class="small text-secondary mt-2">Condividi questo collegamento solo con il cliente o il destinatario.</p><a class="btn btn-outline-primary btn-sm" href="{{ route('tracking.public', $order->tracking_token) }}">Apri tracking cliente <x-ui.icon name="arrow-up-right" /></a>@else<p class="small text-secondary mt-2 mb-0">Il tracking si attiva quando parti per il ritiro.</p>@endif</details>
        </section>
        <details class="surface order-history p-4"><summary class="fw-semibold">Cronologia della spedizione <span class="count-pill">{{ $events->total() }}</span></summary><ol class="tracking-timeline mt-3">@foreach($events as $event)<li><strong>{{ $event->status->label() }}</strong><div class="small text-secondary">{{ $event->created_at->timezone('Europe/Rome')->format('d/m/Y H:i') }} · {{ $event->user->name }}</div>@if($event->note)<p class="mb-1 text-break">{{ $event->note }}</p>@endif @if($event->public_note)<p class="small mb-0 text-break">Pubblico: {{ $event->public_note }}</p>@endif</li>@endforeach</ol>{{ $events->links() }}</details>
    </div>
</x-app-layout>
