<x-app-layout title="Dettaglio ordine">
    <header class="mb-4"><a href="{{ route('orders.incoming') }}" class="small">Ordini</a><h1 class="h3 mt-2 text-break">{{ $order->reference }}</h1><p class="text-secondary">{{ $order->store_name }} · {{ $order->status->label() }}</p></header>
    <div class="row g-4"><div class="col-xl-7"><x-orders.card :order="$order" />
        <section class="surface p-4 mb-4"><h2 class="h5">Dettagli della spedizione</h2><dl class="row mb-0"><dt class="col-sm-5">Destinatario</dt><dd class="col-sm-7">{{ $order->recipient_name }} · {{ $order->recipient_phone }}</dd><dt class="col-sm-5">Contatto negozio</dt><dd class="col-sm-7">{{ $order->contact_email ?: 'Non indicato' }}</dd><dt class="col-sm-5">Categoria</dt><dd class="col-sm-7">{{ ['clothing'=>'Abbigliamento','documents'=>'Documenti','other'=>'Altro'][$order->category] }}</dd><dt class="col-sm-5">Fascia di consegna</dt><dd class="col-sm-7">{{ $order->delivery_window ?: 'Non indicata' }}</dd><dt class="col-sm-5">Importo concordato</dt><dd class="col-sm-7">{{ \App\Support\Money::format($order->price_cents) }}</dd><dt class="col-sm-5">Rider</dt><dd class="col-sm-7">{{ $order->rider?->name ?: 'Da assegnare' }}</dd><dt class="col-sm-5">Istruzioni del cliente</dt><dd class="col-sm-7 text-break">{{ $order->customer_notes ?: 'Nessuna indicazione' }}</dd><dt class="col-sm-5">Note interne</dt><dd class="col-sm-7 text-break">{{ $order->notes ?: 'Nessuna nota' }}</dd></dl></section>
        <section class="surface p-4 mb-4"><h2 class="h5">Tracking cliente</h2>@if($order->tracking_started_at)<p class="small text-secondary">Condividi questo link solo con il cliente o il destinatario.</p><a class="text-break" href="{{ route('tracking.public', $order->tracking_token) }}">{{ route('tracking.public', $order->tracking_token) }}</a>@else<p class="text-secondary mb-0">Il link si attiva quando imposti “Rider in arrivo”.</p>@endif</section>
        @if(Route::has('messages.show'))<a class="btn btn-outline-primary mb-4" href="{{ route('messages.show', $order) }}"><x-ui.icon name="chat-dots" /> Conversazione dell’ordine</a>@endif
    </div><div class="col-xl-5">
    @can('update', $order)
        @if(count($transitions) && ($order->status !== \App\OrderStatus::Rejected || $order->recoverable()))
        <section class="surface p-4 mb-4"><h2 class="h5">Aggiorna spedizione</h2><form method="post" action="{{ route('orders.update', $order) }}" class="form-stack">@csrf @method('patch')<input type="hidden" name="version" value="{{ $order->version }}">
            @if($order->status === \App\OrderStatus::Received)<x-ui.field name="price" label="Importo concordato (€), per accettare" inputmode="decimal" :value="old('price')" placeholder="Es. 8,50" />@endif
            <div><label for="note" class="form-label">Nota interna / motivo</label><textarea id="note" name="note" class="form-control" maxlength="2000" rows="2" aria-describedby="note-help">{{ old('note') }}</textarea><small id="note-help" class="text-secondary">Obbligatoria per rifiuto, annullamento, imprevisto o riprogrammazione.</small></div>
            <div><label for="public_note" class="form-label">Aggiornamento visibile nel tracking (facoltativo)</label><textarea id="public_note" name="public_note" class="form-control" maxlength="500" rows="2">{{ old('public_note') }}</textarea></div>
            <x-ui.field name="estimated_at" label="Nuova previsione (ora italiana)" type="datetime-local" :value="old('estimated_at')" help="Obbligatoria per riprogrammare. Le previsioni non sono garanzie di consegna." />
            <div class="d-flex flex-wrap gap-2">@foreach($transitions as $next)<button name="status" value="{{ $next->value }}" class="btn {{ $next === \App\OrderStatus::Accepted ? 'btn-success' : ($next === \App\OrderStatus::Rejected ? 'btn-danger' : 'btn-outline-primary') }}">@if($next === \App\OrderStatus::Accepted)<x-ui.icon name="check-circle" /> Accetta @elseif($next === \App\OrderStatus::Rejected)<x-ui.icon name="x-circle" /> Rifiuta @elseif($next === \App\OrderStatus::Received)Recupera richiesta @else{{ $next->label() }}@endif</button>@endforeach</div>
        </form></section>@elseif($order->status === \App\OrderStatus::Rejected)<p class="alert alert-secondary">La finestra di un’ora per recuperare la richiesta è scaduta.</p>@endif
    @endcan
    <section class="surface p-4"><h2 class="h5">Storico aggiornamenti</h2><ol class="tracking-timeline mt-3">@foreach($events as $event)<li><strong>{{ $event->status->label() }}</strong><div class="small text-secondary">{{ $event->created_at->timezone('Europe/Rome')->format('d/m/Y H:i') }} · {{ $event->user->name }}</div>@if($event->note)<p class="mb-1 text-break">{{ $event->note }}</p>@endif @if($event->public_note)<p class="small mb-0 text-break">Pubblico: {{ $event->public_note }}</p>@endif</li>@endforeach</ol>{{ $events->links() }}</section>
    </div></div>
</x-app-layout>
